apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # ArgoCD base configuration
  application.instanceLabelKey: argocd.argoproj.io/instance
  server.rbac.log.enforce.enable: "false"
  policy.default: role:readonly
  policy.csv: |
    p, role:admin, applications, *, */*, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow
    g, argocd-admins, role:admin
  # External URL
  url: https://argocd.local
  # GitHub OIDC configuration removed; use only dex.config for GitHub authentication
  # Dex configuration for GitHub
  dex.config: |
    connectors:
      - type: github
        id: github
        name: GitHub
        config:
          clientID: Ov23liLk7cJcNYInr2w5
          clientSecret: $oidc.github.clientSecret
          redirectURI: https://argocd.local/api/dex/callback
          # Permitir todos los usuarios autenticados de GitHub
          # Si quieres restringir a una organización específica, agrega:
          # orgs:
          # - name: tu-organizacion
