apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: trii-platform
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres (base64)
  password: cG9zdGdyZXM=  # postgres (base64)
  database: dHJpaV9kZXY=  # trii_dev (base64)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: trii-platform
data:
  POSTGRES_DB: trii_dev
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: trii-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: trii-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: postgres-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: trii-platform
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432