apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://localhost:8080

  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: Ov23liLk7cJcNYInr2w5
        clientSecret: GITHUB_CLIENT_SECRET
        orgs:
        - name: TU_ORG_GITHUB
