apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: analysis-engine
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Portfolio-jaime/INVESTMENT-APP.git
    path: infrastructure/helm/analysis-engine
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: jaimehenao8126/trii-analysis-engine
          tag: "replace-me-with-commit-hash"
          pullPolicy: Always
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: trii-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true