apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
data:
  url: aHR0cHM6Ly9naXRodWIuY29tL1BvcnRmb2xpbzpqYWltZS9JTlZFU1RNRU5ULUFQUAo=  # base64 of https://github.com/Portfolio-jaime/INVESTMENT-APP
  username: UG9ydGZvbGlvLWphaW1l  # base64 of Portfolio-jaime (assuming username)
  password: <BASE64_ENCODED_PAT>  # Replace with base64 encoded GitHub Personal Access Token