apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: market-data
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Portfolio-jaime/INVESTMENT-APP.git
    path: infrastructure/helm/market-data
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: jaimehenao8126/trii-market-data
          tag: "replace-me-with-commit-hash"
          pullPolicy: Always
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: trii-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true