apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml-prediction
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Portfolio-jaime/INVESTMENT-APP.git
    path: infrastructure/helm/ml-prediction
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: jaimehenao8126/trii-ml-prediction
          tag: "replace-me-with-commit-hash"
          pullPolicy: Always
        resources:
          limits:
            cpu: 2000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 2Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: trii-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true