apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Portfolio-jaime/INVESTMENT-APP # Replace with your GitHub repository URL
    targetRevision: HEAD
    path: helm/database/mongodb
  destination:
    server: https://kubernetes.default.svc
    namespace: default # Deploy MongoDB in the default namespace for simplicity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
