apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-manager
  namespace: argocd
spec:
  project: trii-platform
  source:
    repoURL: https://github.com/Portfolio-jaime/INVESTMENT-APP
    targetRevision: main
    path: helm/charts/portfolio-manager
    helm:
      valueFiles:
        - ../../values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: trii-services
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10