apiVersion: v1
kind: Namespace
metadata:
  name: trii-monitoring
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: trii-platform
    managed-by: argocd
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: trii-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: credentials
type: Opaque
data:
  # Default credentials - CHANGE IN PRODUCTION
  # admin / trii2026!
  admin-user: YWRtaW4=
  admin-password: dHJpaTIwMjYh
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-datasource-credentials
  namespace: trii-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: datasources
type: Opaque
data:
  # Prometheus URL (internal cluster)
  prometheus-url: aHR0cDovL3Byb21ldGhldXMtc2VydmVyLnRyaWktbW9uaXRvcmluZy5zdmMuY2x1c3Rlci5sb2NhbDo4MA==
  # Loki URL (internal cluster) 
  loki-url: aHR0cDovL2xva2kuZGVmYXVsdC5zdmMuY2x1c3Rlci5sb2NhbDozMTAw
  # Jaeger URL (internal cluster)
  jaeger-url: aHR0cDovL2phZWdlci1xdWVyeS50cmlpLW1vbml0b3Jpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6MTY2ODY=
---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-credentials
  namespace: trii-monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: server
type: Opaque
data:
  # Basic auth for Prometheus (if enabled)
  # admin / prometheus2026!
  username: YWRtaW4=
  password: cHJvbWV0aGV1czIwMjYh
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-credentials
  namespace: trii-monitoring
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/component: server
type: Opaque
stringData:
  slack-webhook-url: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  pagerduty-service-key: "your-pagerduty-service-key"
  smtp-password: "your-smtp-password"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  namespace: trii-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboards
data:
  providers.yaml: |
    apiVersion: 1
    providers:
    - name: 'trii-business-dashboards'
      orgId: 1
      folder: 'TRII Business'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/business
    - name: 'trii-technical-dashboards'
      orgId: 1
      folder: 'TRII Technical'
      type: file
      disableDeletion: true
      editable: true
      options:
        path: /var/lib/grafana/dashboards/technical
    - name: 'kubernetes-dashboards'
      orgId: 1
      folder: 'Kubernetes'
      type: file
      disableDeletion: false
      editable: false
      options:
        path: /var/lib/grafana/dashboards/kubernetes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: trii-monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: datasources
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.trii-monitoring.svc.cluster.local:80
      isDefault: true
      editable: true
      jsonData:
        timeInterval: 5s
        httpMethod: POST
    - name: Loki
      type: loki
      access: proxy
      url: http://loki.trii-monitoring.svc.cluster.local:3100
      editable: true
      jsonData:
        maxLines: 1000
    - name: Jaeger
      type: jaeger
      access: proxy
      url: http://jaeger-query.trii-monitoring.svc.cluster.local:16686
      editable: true
      jsonData:
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: '-1h'
          spanEndTimeShift: '1h'
          tags: ['job', 'instance', 'pod', 'namespace']
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: '{$${__tags}} |="$${__trace.traceId}"'
    - name: AlertManager
      type: alertmanager
      access: proxy
      url: http://alertmanager.trii-monitoring.svc.cluster.local:9093
      editable: true
      jsonData:
        implementation: prometheus